title: Md Sazidur Rahman
email: md.s.rahman@uis.no
baseurl: ""
url: "https://yokko123.github.io"
markdown: kramdown
theme: minima
collections:
  projects:
    output: true
  news:
    output: true
  publications:
    output: true
permalink: /:collection/:name/
