title: Your Name
email: your@email.com
baseurl: ""
url: "https://yourusername.github.io"
markdown: kramdown
theme: minima
collections:
  projects:
    output: true
  news:
    output: true
  publications:
    output: true
permalink: /:collection/:name/
